[theme]
# Thème Dark Mode "SaaS / Tech"
base="dark"

# Couleur d'accentuation (violet)
primaryColor="#A78BFA" 

# Fond principal (très sombre)
backgroundColor="#0F172A" # Slate 900

# Fond secondaire (cartes, sidebar, etc.)
secondaryBackgroundColor="#1E293B" # Slate 800

# Couleur de texte principale
textColor="#F8FAFC" # Slate 50

# Police
font="sans serif"
