[theme]
base="dark"
primaryColor="#667eea"
backgroundColor="#0b1220"            # fond sombre (plus de blanc)
secondaryBackgroundColor="#1e293b"   # panneaux/cartes
textColor="#e5e7eb"                  # texte lisible sur fond sombre
font="sans serif"
